# Generated by Django 5.2.5 on 2025-08-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0003_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
