# Generated by Django 5.2.5 on 2025-08-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogafeatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogacourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/'),
        ),
        migrations.AddField(
            model_name='yogaplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/'),
        ),
    ]
